dropna and fillna

In [3]:
import pandas as pd
csv_file=pd.read_csv("C:\\Users\\DELL\\Downloads\\employees.csv")

In [4]:
csv_file

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi      NaN  Marketing         1.0
8    9      Vikas  28.0    Male        NaN  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0        NaN         2.0
10  11      Rohit  30.0    Male  Bangalore  72000.0    Finance         NaN
11  12      Sneha   NaN  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
15  16      Pooja  23.0  Female    Kolkata  45000.0         HR         NaN
16  17      Ayush  26.0    Male  Bangalore      NaN         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female        NaN  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0        NaN         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
27  28       Isha  24.0  Female       Pune  47000.0  Marketing         NaN
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi      NaN         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash   NaN    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai      NaN    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
42  43     Gaurav  28.0    Male       Pune  67000.0    Finance         NaN
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai      NaN  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [5]:
csv_file.dropna()

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [6]:
csv_file.dropna(axis=1)

    id       name  gender
0    1       Siya  Female
1    2       Aman    Male
2    3      Rahul    Male
3    4      Priya  Female
4    5      Karan    Male
5    6       Neha  Female
6    7      Arjun    Male
7    8      Meera  Female
8    9      Vikas    Male
9   10     Anjali  Female
10  11      Rohit    Male
11  12      Sneha  Female
12  13     Aditya    Male
13  14      Kavya  Female
14  15     Manish    Male
15  16      Pooja  Female
16  17      Ayush    Male
17  18     Ritika  Female
18  19     Sachin    Male
19  20      Divya  Female
20  21     Nikhil    Male
21  22     Simran  Female
22  23      Harsh    Male
23  24      Tanya  Female
24  25   Abhishek    Male
25  26      Komal  Female
26  27       Yash    Male
27  28       Isha  Female
28  29      Rajat    Male
29  30     Muskan  Female
30  31     Deepak    Male
31  32      Naina  Female
32  33      Varun    Male
33  34     Shreya  Female
34  35      Akash    Male
35  36      Payal  Female
36  37      Mohit    Male
37  38      Sonal  Female
38  39      Tarun    Male
39  40       Riya  Female
40  41  Siddharth    Male
41  42      Aarti  Female
42  43     Gaurav    Male
43  44      Nidhi  Female
44  45     Pranav    Male
45  46     Sakshi  Female
46  47      Ankit    Male
47  48     Bhavna  Female
48  49     Ramesh    Male
49  50      Kirti  Female

In [7]:
csv_file.dropna(axis=0)

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [9]:
csv_file.dropna(how='any')

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [10]:
csv_file.dropna(how='all')

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi      NaN  Marketing         1.0
8    9      Vikas  28.0    Male        NaN  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0        NaN         2.0
10  11      Rohit  30.0    Male  Bangalore  72000.0    Finance         NaN
11  12      Sneha   NaN  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
15  16      Pooja  23.0  Female    Kolkata  45000.0         HR         NaN
16  17      Ayush  26.0    Male  Bangalore      NaN         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female        NaN  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0        NaN         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
27  28       Isha  24.0  Female       Pune  47000.0  Marketing         NaN
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi      NaN         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash   NaN    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai      NaN    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
42  43     Gaurav  28.0    Male       Pune  67000.0    Finance         NaN
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai      NaN  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [11]:
#to remove nan value alog a praticular column
csv_file.dropna(subset=['experience'])

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi      NaN  Marketing         1.0
8    9      Vikas  28.0    Male        NaN  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0        NaN         2.0
11  12      Sneha   NaN  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
16  17      Ayush  26.0    Male  Bangalore      NaN         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female        NaN  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0        NaN         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi      NaN         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash   NaN    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai      NaN    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai      NaN  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [12]:
#inplace remove all nan value and crete a new dataset
csv_file.dropna(inplace=True)

In [13]:
csv_file

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [16]:
csv_file

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [ ]:
csv_file.dropna(thresh=1) #remove the rows with the single nan value

In [17]:
csv_file=pd.read_csv("C:\\Users\\DELL\\Downloads\\employees.csv")

In [18]:
csv_file

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi      NaN  Marketing         1.0
8    9      Vikas  28.0    Male        NaN  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0        NaN         2.0
10  11      Rohit  30.0    Male  Bangalore  72000.0    Finance         NaN
11  12      Sneha   NaN  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
15  16      Pooja  23.0  Female    Kolkata  45000.0         HR         NaN
16  17      Ayush  26.0    Male  Bangalore      NaN         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female        NaN  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0        NaN         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
27  28       Isha  24.0  Female       Pune  47000.0  Marketing         NaN
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi      NaN         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash   NaN    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai      NaN    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
42  43     Gaurav  28.0    Male       Pune  67000.0    Finance         NaN
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai      NaN  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [19]:
csv_file.fillna('python')

    id       name     age  gender       city   salary department experience
0    1       Siya    23.0  Female      Delhi  45000.0         HR        2.0
1    2       Aman    25.0    Male     Mumbai  52000.0         IT        3.0
2    3      Rahul    27.0    Male       Pune  60000.0    Finance        5.0
3    4      Priya    24.0  Female  Bangalore  48000.0  Marketing        2.0
4    5      Karan    29.0    Male  Hyderabad  75000.0         IT        6.0
5    6       Neha    26.0  Female    Chennai  54000.0         HR        4.0
6    7      Arjun    31.0    Male    Kolkata  82000.0    Finance        8.0
7    8      Meera    22.0  Female      Delhi   python  Marketing        1.0
8    9      Vikas    28.0    Male     python  67000.0         IT        5.0
9   10     Anjali    24.0  Female       Pune  50000.0     python        2.0
10  11      Rohit    30.0    Male  Bangalore  72000.0    Finance     python
11  12      Sneha  python  Female     Mumbai  49000.0         HR        3.0
12  13     Aditya    27.0    Male      Delhi  61000.0         IT        4.0
13  14      Kavya    25.0  Female  Hyderabad  53000.0  Marketing        3.0
14  15     Manish    29.0    Male    Chennai  71000.0    Finance        6.0
15  16      Pooja    23.0  Female    Kolkata  45000.0         HR     python
16  17      Ayush    26.0    Male  Bangalore   python         IT        4.0
17  18     Ritika    24.0  Female      Delhi  48000.0  Marketing        2.0
18  19     Sachin    32.0    Male     Mumbai  90000.0    Finance        9.0
19  20      Divya    27.0  Female       Pune  56000.0         HR        5.0
20  21     Nikhil    28.0    Male  Hyderabad  68000.0         IT        5.0
21  22     Simran    25.0  Female     python  51000.0  Marketing        3.0
22  23      Harsh    31.0    Male    Chennai  83000.0    Finance        8.0
23  24      Tanya    22.0  Female    Kolkata  44000.0         HR        1.0
24  25   Abhishek    30.0    Male      Delhi  76000.0         IT        7.0
25  26      Komal    26.0  Female  Bangalore  55000.0     python        4.0
26  27       Yash    29.0    Male     Mumbai  70000.0    Finance        6.0
27  28       Isha    24.0  Female       Pune  47000.0  Marketing     python
28  29      Rajat    27.0    Male  Hyderabad  64000.0         IT        5.0
29  30     Muskan    23.0  Female      Delhi   python         HR        2.0
30  31     Deepak    33.0    Male  Bangalore  95000.0    Finance       10.0
31  32      Naina    25.0  Female    Chennai  52000.0  Marketing        3.0
32  33      Varun    28.0    Male    Kolkata  69000.0         IT        5.0
33  34     Shreya    24.0  Female     Mumbai  50000.0         HR        2.0
34  35      Akash  python    Male       Pune  62000.0    Finance        4.0
35  36      Payal    27.0  Female  Hyderabad  57000.0  Marketing        5.0
36  37      Mohit    30.0    Male      Delhi  78000.0         IT        7.0
37  38      Sonal    22.0  Female  Bangalore  43000.0         HR        1.0
38  39      Tarun    29.0    Male    Chennai   python    Finance        6.0
39  40       Riya    26.0  Female    Kolkata  54000.0  Marketing        4.0
40  41  Siddharth    31.0    Male     Mumbai  85000.0         IT        8.0
41  42      Aarti    25.0  Female      Delhi  51000.0         HR        3.0
42  43     Gaurav    28.0    Male       Pune  67000.0    Finance     python
43  44      Nidhi    24.0  Female  Hyderabad  49000.0  Marketing        2.0
44  45     Pranav    32.0    Male  Bangalore  92000.0         IT        9.0
45  46     Sakshi    23.0  Female    Chennai  46000.0         HR        1.0
46  47      Ankit    27.0    Male    Kolkata  63000.0    Finance        5.0
47  48     Bhavna    26.0  Female     Mumbai   python  Marketing        4.0
48  49     Ramesh    30.0    Male      Delhi  74000.0         IT        7.0
49  50      Kirti    25.0  Female       Pune  52000.0         HR        3.0

In [ ]:
csv_file.fillna({'age':21,'salary':30000}) #fill the nan value of the particular column

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi  30000.0  Marketing         1.0
8    9      Vikas  28.0    Male        NaN  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0        NaN         2.0
10  11      Rohit  30.0    Male  Bangalore  72000.0    Finance         NaN
11  12      Sneha  21.0  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
15  16      Pooja  23.0  Female    Kolkata  45000.0         HR         NaN
16  17      Ayush  26.0    Male  Bangalore  30000.0         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female        NaN  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0        NaN         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
27  28       Isha  24.0  Female       Pune  47000.0  Marketing         NaN
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi  30000.0         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash  21.0    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai  30000.0    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
42  43     Gaurav  28.0    Male       Pune  67000.0    Finance         NaN
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai  30000.0  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [22]:
#fill the nan value with previous or forward value
csv_file.ffill()

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi  82000.0  Marketing         1.0
8    9      Vikas  28.0    Male      Delhi  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0         IT         2.0
10  11      Rohit  30.0    Male  Bangalore  72000.0    Finance         2.0
11  12      Sneha  30.0  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
15  16      Pooja  23.0  Female    Kolkata  45000.0         HR         6.0
16  17      Ayush  26.0    Male  Bangalore  45000.0         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female  Hyderabad  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0         IT         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
27  28       Isha  24.0  Female       Pune  47000.0  Marketing         6.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi  64000.0         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash  24.0    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai  43000.0    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
42  43     Gaurav  28.0    Male       Pune  67000.0    Finance         3.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai  63000.0  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0

In [23]:
csv_file.bfill()

    id       name   age  gender       city   salary department  experience
0    1       Siya  23.0  Female      Delhi  45000.0         HR         2.0
1    2       Aman  25.0    Male     Mumbai  52000.0         IT         3.0
2    3      Rahul  27.0    Male       Pune  60000.0    Finance         5.0
3    4      Priya  24.0  Female  Bangalore  48000.0  Marketing         2.0
4    5      Karan  29.0    Male  Hyderabad  75000.0         IT         6.0
5    6       Neha  26.0  Female    Chennai  54000.0         HR         4.0
6    7      Arjun  31.0    Male    Kolkata  82000.0    Finance         8.0
7    8      Meera  22.0  Female      Delhi  67000.0  Marketing         1.0
8    9      Vikas  28.0    Male       Pune  67000.0         IT         5.0
9   10     Anjali  24.0  Female       Pune  50000.0    Finance         2.0
10  11      Rohit  30.0    Male  Bangalore  72000.0    Finance         3.0
11  12      Sneha  27.0  Female     Mumbai  49000.0         HR         3.0
12  13     Aditya  27.0    Male      Delhi  61000.0         IT         4.0
13  14      Kavya  25.0  Female  Hyderabad  53000.0  Marketing         3.0
14  15     Manish  29.0    Male    Chennai  71000.0    Finance         6.0
15  16      Pooja  23.0  Female    Kolkata  45000.0         HR         4.0
16  17      Ayush  26.0    Male  Bangalore  48000.0         IT         4.0
17  18     Ritika  24.0  Female      Delhi  48000.0  Marketing         2.0
18  19     Sachin  32.0    Male     Mumbai  90000.0    Finance         9.0
19  20      Divya  27.0  Female       Pune  56000.0         HR         5.0
20  21     Nikhil  28.0    Male  Hyderabad  68000.0         IT         5.0
21  22     Simran  25.0  Female    Chennai  51000.0  Marketing         3.0
22  23      Harsh  31.0    Male    Chennai  83000.0    Finance         8.0
23  24      Tanya  22.0  Female    Kolkata  44000.0         HR         1.0
24  25   Abhishek  30.0    Male      Delhi  76000.0         IT         7.0
25  26      Komal  26.0  Female  Bangalore  55000.0    Finance         4.0
26  27       Yash  29.0    Male     Mumbai  70000.0    Finance         6.0
27  28       Isha  24.0  Female       Pune  47000.0  Marketing         5.0
28  29      Rajat  27.0    Male  Hyderabad  64000.0         IT         5.0
29  30     Muskan  23.0  Female      Delhi  95000.0         HR         2.0
30  31     Deepak  33.0    Male  Bangalore  95000.0    Finance        10.0
31  32      Naina  25.0  Female    Chennai  52000.0  Marketing         3.0
32  33      Varun  28.0    Male    Kolkata  69000.0         IT         5.0
33  34     Shreya  24.0  Female     Mumbai  50000.0         HR         2.0
34  35      Akash  27.0    Male       Pune  62000.0    Finance         4.0
35  36      Payal  27.0  Female  Hyderabad  57000.0  Marketing         5.0
36  37      Mohit  30.0    Male      Delhi  78000.0         IT         7.0
37  38      Sonal  22.0  Female  Bangalore  43000.0         HR         1.0
38  39      Tarun  29.0    Male    Chennai  54000.0    Finance         6.0
39  40       Riya  26.0  Female    Kolkata  54000.0  Marketing         4.0
40  41  Siddharth  31.0    Male     Mumbai  85000.0         IT         8.0
41  42      Aarti  25.0  Female      Delhi  51000.0         HR         3.0
42  43     Gaurav  28.0    Male       Pune  67000.0    Finance         2.0
43  44      Nidhi  24.0  Female  Hyderabad  49000.0  Marketing         2.0
44  45     Pranav  32.0    Male  Bangalore  92000.0         IT         9.0
45  46     Sakshi  23.0  Female    Chennai  46000.0         HR         1.0
46  47      Ankit  27.0    Male    Kolkata  63000.0    Finance         5.0
47  48     Bhavna  26.0  Female     Mumbai  74000.0  Marketing         4.0
48  49     Ramesh  30.0    Male      Delhi  74000.0         IT         7.0
49  50      Kirti  25.0  Female       Pune  52000.0         HR         3.0