In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[6,7,8,9,10],
    'C':[11,12,13,14,15]
})
data

   A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [3]:
def square(x):
    return x**2

In [5]:
data['D']=data['B'].apply(square)
data

   A   B   C    D
0  1   6  11   36
1  2   7  12   49
2  3   8  13   64
3  4   9  14   81
4  5  10  15  100