groupby-it helps us to make the data in sequence in the datasheets

In [1]:
import pandas as pd

In [4]:
data=pd.DataFrame({'name':['a','b','c','d','e','a','b','g','c'],
                   's1_marks':[81,72,53,94,95,81,72,86,53],
                   's2_marks':[87,65,67,98,67,87,65,67,67]})

In [5]:
data

  name  s1_marks  s2_marks
0    a        81        87
1    b        72        65
2    c        53        67
3    d        94        98
4    e        95        67
5    a        81        87
6    b        72        65
7    g        86        67
8    c        53        67

In [6]:
data_new=data.groupby('name')
data_new

In [7]:
for i,j in data_new:
    print(i)
    print(j)

a
  name  s1_marks  s2_marks
0    a        81        87
5    a        81        87
b
  name  s1_marks  s2_marks
1    b        72        65
6    b        72        65
c
  name  s1_marks  s2_marks
2    c        53        67
8    c        53        67
d
  name  s1_marks  s2_marks
3    d        94        98
e
  name  s1_marks  s2_marks
4    e        95        67
g
  name  s1_marks  s2_marks
7    g        86        67

In [11]:
data_new.get_group(name='a')

  name  s1_marks  s2_marks
0    a        81        87
5    a        81        87

In [12]:
data_new.min()

      s1_marks  s2_marks
name
a           81        87
b           72        65
c           53        67
d           94        98
e           95        67
g           86        67

In [13]:
data_new.max()

      s1_marks  s2_marks
name
a           81        87
b           72        65
c           53        67
d           94        98
e           95        67
g           86        67

In [14]:
data_new.mean()

      s1_marks  s2_marks
name
a         81.0      87.0
b         72.0      65.0
c         53.0      67.0
d         94.0      98.0
e         95.0      67.0
g         86.0      67.0

In [16]:
data_new.sum()

      s1_marks  s2_marks
name
a          162       174
b          144       130
c          106       134
d           94        98
e           95        67
g           86        67

In [20]:
data_new.agg(['min','max','sum','median'])

     s1_marks                 s2_marks
          min max  sum median      min max  sum median
name
a          81  81  162   81.0       87  87  174   87.0
b          72  72  144   72.0       65  65  130   65.0
c          53  53  106   53.0       67  67  134   67.0
d          94  94   94   94.0       98  98   98   98.0
e          95  95   95   95.0       67  67   67   67.0
g          86  86   86   86.0       67  67   67   67.0