In [1]:
import pandas as pd

In [2]:
data1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
data2=pd.DataFrame({'c':[11,12,13,14],'d':[25,26,27,28]})

In [3]:
data1.join(data2)

   A  B   c   d
0  1  5  11  25
1  2  6  12  26
2  3  7  13  27
3  4  8  14  28

In [5]:
data1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
data2=pd.DataFrame({'c':[11,12],'d':[25,26]})

In [9]:
data2.join(data1,how='right')

      c     d  A  B
0  11.0  25.0  1  5
1  12.0  26.0  2  6
2   NaN   NaN  3  7
3   NaN   NaN  4  8

outer works as union and inner works as intersection

In [10]:
data2.join(data1,how='outer')

      c     d  A  B
0  11.0  25.0  1  5
1  12.0  26.0  2  6
2   NaN   NaN  3  7
3   NaN   NaN  4  8

In [11]:
data2.join(data1,how='inner')

    c   d  A  B
0  11  25  1  5
1  12  26  2  6

append(removed from new version) - to make the single dataframe from two or more 
but it is different from join as if the column value is same in join it was giving error but with the help of it we can solve this problem