In [1]:
import pandas as pd

In [10]:
data1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
data2=pd.DataFrame({'A':[1,2,3,5],'c':[15,16,17,18]})

In [11]:
pd.merge(data1,data2,on='A')

   A  B   c
0  1  5  15
1  2  6  16
2  3  7  17

In [12]:
pd.merge(data1,data2,how='left')

   A  B     c
0  1  5  15.0
1  2  6  16.0
2  3  7  17.0
3  4  8   NaN

In [13]:
pd.merge(data1,data2,how='inner')

   A  B   c
0  1  5  15
1  2  6  16
2  3  7  17

In [15]:
pd.merge(data1,data2,how='outer',indicator=True)

   A    B     c      _merge
0  1  5.0  15.0        both
1  2  6.0  16.0        both
2  3  7.0  17.0        both
3  4  8.0   NaN   left_only
4  5  NaN  18.0  right_only

In [19]:
pd.merge(data1,data2,left_index=True,right_index=True,suffixes=('id_1','id'))

   Aid_1  B  Aid   c
0      1  5    1  15
1      2  6    2  16
2      3  7    3  17
3      4  8    5  18

concat

In [20]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([11,12,13,14])

In [22]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [23]:
s2

0    11
1    12
2    13
3    14
dtype: int64

In [25]:
pd.concat([s1,s2])

0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [26]:
d1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
d2=pd.DataFrame({'A':[1,2,3,5],'c':[15,16,17,18]})

In [ ]:
pd.concat([d1,d2])

   A    B     c
0  1  5.0   NaN
1  2  6.0   NaN
2  3  7.0   NaN
3  4  8.0   NaN
0  1  NaN  15.0
1  2  NaN  16.0
2  3  NaN  17.0
3  5  NaN  18.0

In [30]:
pd.concat([d1,d2],axis=1)

   A  B  A   c
0  1  5  1  15
1  2  6  2  16
2  3  7  3  17
3  4  8  5  18

concat using join parameter

In [34]:
pd.concat([d1,d2],join='outer')

   A    B     c
0  1  5.0   NaN
1  2  6.0   NaN
2  3  7.0   NaN
3  4  8.0   NaN
0  1  NaN  15.0
1  2  NaN  16.0
2  3  NaN  17.0
3  5  NaN  18.0

In [35]:
pd.concat([d1,d2],join='inner')

   A
0  1
1  2
2  3
3  4
0  1
1  2
2  3
3  5

concat using key parameter

In [39]:
pd.concat([d1,d2],keys=['d1','d2'])

      A    B     c
d1 0  1  5.0   NaN
   1  2  6.0   NaN
   2  3  7.0   NaN
   3  4  8.0   NaN
d2 0  1  NaN  15.0
   1  2  NaN  16.0
   2  3  NaN  17.0
   3  5  NaN  18.0

In [38]:
pd.concat([d1,d2],keys=['d1','d2'],axis=1)

  d1    d2
   A  B  A   c
0  1  5  1  15
1  2  6  2  16
2  3  7  3  17
3  4  8  5  18