Replace

In [56]:
import pandas as pd
file=pd.read_csv("C:\\Users\\DELL\\Downloads\\sample_data_25x5.csv")

In [57]:
file

    Unnamed: 0  Student_ID        Name  Age  Marks       City
0            0        1001   Student_1   23     57      Delhi
1            1        1002   Student_2   19     96     Mumbai
2            2        1003   Student_3   18     52      Delhi
3            3        1004   Student_4   20     84  Hyderabad
4            4        1005   Student_5   21     53    Chennai
5            5        1006   Student_6   18     85  Bangalore
6            6        1007   Student_7   21     95  Bangalore
7            7        1008   Student_8   22     89  Hyderabad
8            8        1009   Student_9   19     55     Mumbai
9            9        1010  Student_10   18     52      Delhi
10          10        1011  Student_11   23     75  Bangalore
11          11        1012  Student_12   24     63     Mumbai
12          12        1013  Student_13   20     97  Hyderabad
13          13        1014  Student_14   19     52    Chennai
14          14        1015  Student_15   19     64    Chennai
15          15        1016  Student_16   21     73    Chennai
16          16        1017  Student_17   23     91    Chennai
17          17        1018  Student_18   23     88      Delhi
18          18        1019  Student_19   24     97     Mumbai
19          19        1020  Student_20   21     84    Chennai
20          20        1021  Student_21   19     71    Chennai
21          21        1022  Student_22   21     93  Hyderabad
22          22        1023  Student_23   24     73  Hyderabad
23          23        1024  Student_24   19     94    Chennai
24          24        1025  Student_25   20     51  Hyderabad

In [58]:
file.replace(to_replace=21,value=20)

    Unnamed: 0  Student_ID        Name  Age  Marks       City
0            0        1001   Student_1   23     57      Delhi
1            1        1002   Student_2   19     96     Mumbai
2            2        1003   Student_3   18     52      Delhi
3            3        1004   Student_4   20     84  Hyderabad
4            4        1005   Student_5   20     53    Chennai
5            5        1006   Student_6   18     85  Bangalore
6            6        1007   Student_7   20     95  Bangalore
7            7        1008   Student_8   22     89  Hyderabad
8            8        1009   Student_9   19     55     Mumbai
9            9        1010  Student_10   18     52      Delhi
10          10        1011  Student_11   23     75  Bangalore
11          11        1012  Student_12   24     63     Mumbai
12          12        1013  Student_13   20     97  Hyderabad
13          13        1014  Student_14   19     52    Chennai
14          14        1015  Student_15   19     64    Chennai
15          15        1016  Student_16   20     73    Chennai
16          16        1017  Student_17   23     91    Chennai
17          17        1018  Student_18   23     88      Delhi
18          18        1019  Student_19   24     97     Mumbai
19          19        1020  Student_20   20     84    Chennai
20          20        1021  Student_21   19     71    Chennai
21          20        1022  Student_22   20     93  Hyderabad
22          22        1023  Student_23   24     73  Hyderabad
23          23        1024  Student_24   19     94    Chennai
24          24        1025  Student_25   20     51  Hyderabad

In [59]:
file.replace(to_replace='Student_1',value='Sakshi')

    Unnamed: 0  Student_ID        Name  Age  Marks       City
0            0        1001      Sakshi   23     57      Delhi
1            1        1002   Student_2   19     96     Mumbai
2            2        1003   Student_3   18     52      Delhi
3            3        1004   Student_4   20     84  Hyderabad
4            4        1005   Student_5   21     53    Chennai
5            5        1006   Student_6   18     85  Bangalore
6            6        1007   Student_7   21     95  Bangalore
7            7        1008   Student_8   22     89  Hyderabad
8            8        1009   Student_9   19     55     Mumbai
9            9        1010  Student_10   18     52      Delhi
10          10        1011  Student_11   23     75  Bangalore
11          11        1012  Student_12   24     63     Mumbai
12          12        1013  Student_13   20     97  Hyderabad
13          13        1014  Student_14   19     52    Chennai
14          14        1015  Student_15   19     64    Chennai
15          15        1016  Student_16   21     73    Chennai
16          16        1017  Student_17   23     91    Chennai
17          17        1018  Student_18   23     88      Delhi
18          18        1019  Student_19   24     97     Mumbai
19          19        1020  Student_20   21     84    Chennai
20          20        1021  Student_21   19     71    Chennai
21          21        1022  Student_22   21     93  Hyderabad
22          22        1023  Student_23   24     73  Hyderabad
23          23        1024  Student_24   19     94    Chennai
24          24        1025  Student_25   20     51  Hyderabad

In [60]:
file.replace([1,2,3,4,5],25)

    Unnamed: 0  Student_ID        Name  Age  Marks       City
0            0        1001   Student_1   23     57      Delhi
1           25        1002   Student_2   19     96     Mumbai
2           25        1003   Student_3   18     52      Delhi
3           25        1004   Student_4   20     84  Hyderabad
4           25        1005   Student_5   21     53    Chennai
5           25        1006   Student_6   18     85  Bangalore
6            6        1007   Student_7   21     95  Bangalore
7            7        1008   Student_8   22     89  Hyderabad
8            8        1009   Student_9   19     55     Mumbai
9            9        1010  Student_10   18     52      Delhi
10          10        1011  Student_11   23     75  Bangalore
11          11        1012  Student_12   24     63     Mumbai
12          12        1013  Student_13   20     97  Hyderabad
13          13        1014  Student_14   19     52    Chennai
14          14        1015  Student_15   19     64    Chennai
15          15        1016  Student_16   21     73    Chennai
16          16        1017  Student_17   23     91    Chennai
17          17        1018  Student_18   23     88      Delhi
18          18        1019  Student_19   24     97     Mumbai
19          19        1020  Student_20   21     84    Chennai
20          20        1021  Student_21   19     71    Chennai
21          21        1022  Student_22   21     93  Hyderabad
22          22        1023  Student_23   24     73  Hyderabad
23          23        1024  Student_24   19     94    Chennai
24          24        1025  Student_25   20     51  Hyderabad

Replace using regex

In [61]:
file.replace("[A-Za-z]",'python',regex=True)

,Unnamed: 0,Student_ID,Name,Age,Marks,City
0,0,1001,pythonpythonpythonpythonpythonpythonpython_1,23,57,pythonpythonpythonpythonpython
1,1,1002,pythonpythonpythonpythonpythonpythonpython_2,19,96,pythonpythonpythonpythonpythonpython
2,2,1003,pythonpythonpythonpythonpythonpythonpython_3,18,52,pythonpythonpythonpythonpython
3,3,1004,pythonpythonpythonpythonpythonpythonpython_4,20,84,pythonpythonpythonpythonpythonpythonpythonpyth...
4,4,1005,pythonpythonpythonpythonpythonpythonpython_5,21,53,pythonpythonpythonpythonpythonpythonpython
5,5,1006,pythonpythonpythonpythonpythonpythonpython_6,18,85,pythonpythonpythonpythonpythonpythonpythonpyth...
6,6,1007,pythonpythonpythonpythonpythonpythonpython_7,21,95,pythonpythonpythonpythonpythonpythonpythonpyth...
7,7,1008,pythonpythonpythonpythonpythonpythonpython_8,22,89,pythonpythonpythonpythonpythonpythonpythonpyth...
8,8,1009,pythonpythonpythonpythonpythonpythonpython_9,19,55,pythonpythonpythonpythonpythonpython
9,9,1010,pythonpythonpythonpythonpythonpythonpython_10,18,52,pythonpythonpythonpythonpython
10,10,1011,pythonpythonpythonpythonpythonpythonpython_11,23,75,pythonpythonpythonpythonpythonpythonpythonpyth...
11,11,1012,pythonpythonpythonpythonpythonpythonpython_12,24,63,pythonpythonpythonpythonpythonpython
12,12,1013,pythonpythonpythonpythonpythonpythonpython_13,20,97,pythonpythonpythonpythonpythonpythonpythonpyth...
13,13,1014,pythonpythonpythonpythonpythonpythonpython_14,19,52,pythonpythonpythonpythonpythonpythonpython
14,14,1015,pythonpythonpythonpythonpythonpythonpython_15,19,64,pythonpythonpythonpythonpythonpythonpython
15,15,1016,pythonpythonpythonpythonpythonpythonpython_16,21,73,pythonpythonpythonpythonpythonpythonpython
16,16,1017,pythonpythonpythonpythonpythonpythonpython_17,23,91,pythonpythonpythonpythonpythonpythonpython
17,17,1018,pythonpythonpythonpythonpythonpythonpython_18,23,88,pythonpythonpythonpythonpython
18,18,1019,pythonpythonpythonpythonpythonpythonpython_19,24,97,pythonpythonpythonpythonpythonpython
19,19,1020,pythonpythonpythonpythonpythonpythonpython_20,21,84,pythonpythonpythonpythonpythonpythonpython
20,20,1021,pythonpythonpythonpythonpythonpythonpython_21,19,71,pythonpythonpythonpythonpythonpythonpython
21,21,1022,pythonpythonpythonpythonpythonpythonpython_22,21,93,pythonpythonpythonpythonpythonpythonpythonpyth...
22,22,1023,pythonpythonpythonpythonpythonpythonpython_23,24,73,pythonpythonpythonpythonpythonpythonpythonpyth...
23,23,1024,pythonpythonpythonpythonpythonpythonpython_24,19,94,pythonpythonpythonpythonpythonpythonpython
24,24,1025,pythonpythonpythonpythonpythonpythonpython_25,20,51,pythonpythonpythonpythonpythonpythonpythonpyth...

Replace using dictionary

In [62]:
file.replace({'Name':'[A-Z]'},22,regex=True)

    Unnamed: 0  Student_ID Name  Age  Marks       City
0            0        1001   22   23     57      Delhi
1            1        1002   22   19     96     Mumbai
2            2        1003   22   18     52      Delhi
3            3        1004   22   20     84  Hyderabad
4            4        1005   22   21     53    Chennai
5            5        1006   22   18     85  Bangalore
6            6        1007   22   21     95  Bangalore
7            7        1008   22   22     89  Hyderabad
8            8        1009   22   19     55     Mumbai
9            9        1010   22   18     52      Delhi
10          10        1011   22   23     75  Bangalore
11          11        1012   22   24     63     Mumbai
12          12        1013   22   20     97  Hyderabad
13          13        1014   22   19     52    Chennai
14          14        1015   22   19     64    Chennai
15          15        1016   22   21     73    Chennai
16          16        1017   22   23     91    Chennai
17          17        1018   22   23     88      Delhi
18          18        1019   22   24     97     Mumbai
19          19        1020   22   21     84    Chennai
20          20        1021   22   19     71    Chennai
21          21        1022   22   21     93  Hyderabad
22          22        1023   22   24     73  Hyderabad
23          23        1024   22   19     94    Chennai
24          24        1025   22   20     51  Hyderabad

In [63]:
import numpy as np
file.replace(52,np.nan).ffill()

    Unnamed: 0  Student_ID Name  Age  Marks       City
0            0        1001   22   23   57.0      Delhi
1            1        1002   22   19   96.0     Mumbai
2            2        1003   22   18   96.0      Delhi
3            3        1004   22   20   84.0  Hyderabad
4            4        1005   22   21   53.0    Chennai
5            5        1006   22   18   85.0  Bangalore
6            6        1007   22   21   95.0  Bangalore
7            7        1008   22   22   89.0  Hyderabad
8            8        1009   22   19   55.0     Mumbai
9            9        1010   22   18   55.0      Delhi
10          10        1011   22   23   75.0  Bangalore
11          11        1012   22   24   63.0     Mumbai
12          12        1013   22   20   97.0  Hyderabad
13          13        1014   22   19   97.0    Chennai
14          14        1015   22   19   64.0    Chennai
15          15        1016   22   21   73.0    Chennai
16          16        1017   22   23   91.0    Chennai
17          17        1018   22   23   88.0      Delhi
18          18        1019   22   24   97.0     Mumbai
19          19        1020   22   21   84.0    Chennai
20          20        1021   22   19   71.0    Chennai
21          21        1022   22   21   93.0  Hyderabad
22          22        1023   22   24   73.0  Hyderabad
23          23        1024   22   19   94.0    Chennai
24          24        1025   22   20   51.0  Hyderabad

In [64]:
file.replace(1023,np.nan).bfill()

    Unnamed: 0  Student_ID Name  Age  Marks       City
0            0      1001.0   22   23     57      Delhi
1            1      1002.0   22   19     96     Mumbai
2            2      1003.0   22   18     52      Delhi
3            3      1004.0   22   20     84  Hyderabad
4            4      1005.0   22   21     53    Chennai
5            5      1006.0   22   18     85  Bangalore
6            6      1007.0   22   21     95  Bangalore
7            7      1008.0   22   22     89  Hyderabad
8            8      1009.0   22   19     55     Mumbai
9            9      1010.0   22   18     52      Delhi
10          10      1011.0   22   23     75  Bangalore
11          11      1012.0   22   24     63     Mumbai
12          12      1013.0   22   20     97  Hyderabad
13          13      1014.0   22   19     52    Chennai
14          14      1015.0   22   19     64    Chennai
15          15      1016.0   22   21     73    Chennai
16          16      1017.0   22   23     91    Chennai
17          17      1018.0   22   23     88      Delhi
18          18      1019.0   22   24     97     Mumbai
19          19      1020.0   22   21     84    Chennai
20          20      1021.0   22   19     71    Chennai
21          21      1022.0   22   21     93  Hyderabad
22          22      1024.0   22   24     73  Hyderabad
23          23      1024.0   22   19     94    Chennai
24          24      1025.0   22   20     51  Hyderabad

Repace using limit - not present in newer version of pandas(gives error)

In [65]:
file.replace(22,'sakshi',limit=4)

TypeError: NDFrame.replace() got an unexpected keyword argument 'limit'

In [ ]:
file.replace(22,'sakshi',inplace=True)

   Unnamed: 0  Student_ID Name     Age  Marks       City
0           0        1001   22      23     57      Delhi
1           1        1002   22      19     96     Mumbai
2           2        1003   22      18     52      Delhi
3           3        1004   22      20     84  Hyderabad
4           4        1005   22      21     53    Chennai
5           5        1006   22      18     85  Bangalore
6           6        1007   22      21     95  Bangalore
7           7        1008   22  sakshi     89  Hyderabad
8           8        1009   22      19     55     Mumbai
9           9        1010   22      18     52      Delhi
10         10        1011   22      23     75  Bangalore
11         11        1012   22      24     63     Mumbai
12         12        1013   22      20     97  Hyderabad
13         13        1014   22      19     52    Chennai
14         14        1015   22      19     64    Chennai
15         15        1016   22      21     73    Chennai
16         16        1017   22      23     91    Chennai
17         17        1018   22      23     88      Delhi
18         18        1019   22      24     97     Mumbai
19         19        1020   22      21     84    Chennai
20         20        1021   22      19     71    Chennai
21         21        1022   22      21     93  Hyderabad
22     sakshi        1023   22      24     73  Hyderabad
23         23        1024   22      19     94    Chennai
24         24        1025   22      20     51  Hyderabad

interpolate[mainly works with numeric column]-it is used to fill the missing data ,not randomly but after the obseving its sequence values

In [83]:
csv_file=pd.read_csv('students_missing_data.csv')

In [67]:
csv_file

    Student_ID    Name   Age  Marks       City
0         1001    Aman  22.0   85.0      Delhi
1         1002   Priya  21.0    NaN     Mumbai
2         1003   Rahul   NaN   78.0  Bangalore
3         1004   Sneha  23.0   92.0        NaN
4         1005   Arjun  20.0   67.0    Chennai
5         1006     NaN  22.0   74.0  Hyderabad
6         1007   Meena  21.0    NaN       Pune
7         1008   Karan  24.0   88.0    Kolkata
8         1009  Anjali   NaN   95.0      Delhi
9         1010   Rohit  22.0   56.0        NaN
10        1011   Pooja  23.0   81.0     Mumbai
11        1012   Vikas  20.0    NaN  Bangalore
12        1013    Neha   NaN   73.0    Chennai
13        1014   Sahil  21.0   64.0  Hyderabad
14        1015   Divya  22.0    NaN       Pune
15        1016   Ayush  24.0   90.0    Kolkata
16        1017  Ritika   NaN   85.0        NaN
17        1018  Manish  20.0   58.0      Delhi
18        1019   Komal  23.0    NaN     Mumbai
19        1020   Nitin  21.0   76.0  Bangalore
20        1021  Simran   NaN   89.0    Chennai
21        1022   Varun  22.0   61.0        NaN
22        1023   Tanya  20.0    NaN       Pune
23        1024  Deepak  24.0   94.0    Kolkata
24        1025   Kavya   NaN   72.0      Delhi

In [68]:
csv_file["Marks"]=csv_file["Marks"].interpolate()

csv_file["Age"]=csv_file["Age"].interpolate()

In [69]:
csv_file

    Student_ID    Name   Age  Marks       City
0         1001    Aman  22.0   85.0      Delhi
1         1002   Priya  21.0   81.5     Mumbai
2         1003   Rahul  22.0   78.0  Bangalore
3         1004   Sneha  23.0   92.0        NaN
4         1005   Arjun  20.0   67.0    Chennai
5         1006     NaN  22.0   74.0  Hyderabad
6         1007   Meena  21.0   81.0       Pune
7         1008   Karan  24.0   88.0    Kolkata
8         1009  Anjali  23.0   95.0      Delhi
9         1010   Rohit  22.0   56.0        NaN
10        1011   Pooja  23.0   81.0     Mumbai
11        1012   Vikas  20.0   77.0  Bangalore
12        1013    Neha  20.5   73.0    Chennai
13        1014   Sahil  21.0   64.0  Hyderabad
14        1015   Divya  22.0   77.0       Pune
15        1016   Ayush  24.0   90.0    Kolkata
16        1017  Ritika  22.0   85.0        NaN
17        1018  Manish  20.0   58.0      Delhi
18        1019   Komal  23.0   67.0     Mumbai
19        1020   Nitin  21.0   76.0  Bangalore
20        1021  Simran  21.5   89.0    Chennai
21        1022   Varun  22.0   61.0        NaN
22        1023   Tanya  20.0   77.5       Pune
23        1024  Deepak  24.0   94.0    Kolkata
24        1025   Kavya  24.0   72.0      Delhi

In [70]:
csv_file=csv_file['Age'].interpolate(method='quadratic')

In [71]:
csv_file

0     22.0
1     21.0
2     22.0
3     23.0
4     20.0
5     22.0
6     21.0
7     24.0
8     23.0
9     22.0
10    23.0
11    20.0
12    20.5
13    21.0
14    22.0
15    24.0
16    22.0
17    20.0
18    23.0
19    21.0
20    21.5
21    22.0
22    20.0
23    24.0
24    24.0
Name: Age, dtype: float64

In [74]:
csv_file["Age"] = csv_file["Age"].interpolate(method='linear',limit=1)

In [88]:
csv_file

    Student_ID    Name   Age  Marks       City
0         1001    Aman  22.0   85.0      Delhi
1         1002   Priya  21.0   81.5     Mumbai
2         1003   Rahul   NaN   78.0  Bangalore
3         1004   Sneha  23.0   92.0        NaN
4         1005   Arjun  20.0   67.0    Chennai
5         1006     NaN  22.0   74.0  Hyderabad
6         1007   Meena  21.0   81.0       Pune
7         1008   Karan  24.0   88.0    Kolkata
8         1009  Anjali   NaN   95.0      Delhi
9         1010   Rohit  22.0   56.0        NaN
10        1011   Pooja  23.0   81.0     Mumbai
11        1012   Vikas  20.0   77.0  Bangalore
12        1013    Neha   NaN   73.0    Chennai
13        1014   Sahil  21.0   64.0  Hyderabad
14        1015   Divya  22.0   77.0       Pune
15        1016   Ayush  24.0   90.0    Kolkata
16        1017  Ritika   NaN   85.0        NaN
17        1018  Manish  20.0   58.0      Delhi
18        1019   Komal  23.0   67.0     Mumbai
19        1020   Nitin  21.0   76.0  Bangalore
20        1021  Simran   NaN   89.0    Chennai
21        1022   Varun  22.0   61.0        NaN
22        1023   Tanya  20.0   77.5       Pune
23        1024  Deepak  24.0   94.0    Kolkata
24        1025   Kavya   NaN   72.0      Delhi

In [90]:
csv_file['Marks'].interpolate(limit_direction='forward',limit=2)

0     85.0
1     81.5
2     78.0
3     92.0
4     67.0
5     74.0
6     81.0
7     88.0
8     95.0
9     56.0
10    81.0
11    77.0
12    73.0
13    64.0
14    77.0
15    90.0
16    85.0
17    58.0
18    67.0
19    76.0
20    89.0
21    61.0
22    77.5
23    94.0
24    72.0
Name: Marks, dtype: float64

In [92]:
csv_file['Age']=csv_file['Age'].interpolate(method='linear',limit=1,limit_direction='both')

In [94]:
print(csv_file)

    Student_ID    Name   Age  Marks       City
0         1001    Aman  22.0   85.0      Delhi
1         1002   Priya  21.0   81.5     Mumbai
2         1003   Rahul  22.0   78.0  Bangalore
3         1004   Sneha  23.0   92.0        NaN
4         1005   Arjun  20.0   67.0    Chennai
5         1006     NaN  22.0   74.0  Hyderabad
6         1007   Meena  21.0   81.0       Pune
7         1008   Karan  24.0   88.0    Kolkata
8         1009  Anjali  23.0   95.0      Delhi
9         1010   Rohit  22.0   56.0        NaN
10        1011   Pooja  23.0   81.0     Mumbai
11        1012   Vikas  20.0   77.0  Bangalore
12        1013    Neha  20.5   73.0    Chennai
13        1014   Sahil  21.0   64.0  Hyderabad
14        1015   Divya  22.0   77.0       Pune
15        1016   Ayush  24.0   90.0    Kolkata
16        1017  Ritika  22.0   85.0        NaN
17        1018  Manish  20.0   58.0      Delhi
18        1019   Komal  23.0   67.0     Mumbai
19        1020   Nitin  21.0   76.0  Bangalore
20        1021  Simran  21.5   89.0    Chennai
21        1022   Varun  22.0   61.0        NaN
22        1023   Tanya  20.0   77.5       Pune
23        1024  Deepak  24.0   94.0    Kolkata
24        1025   Kavya  24.0   72.0      Delhi

In [96]:
csv_file=pd.read_csv("students_missing_data.csv")

In [97]:
csv_file

    Student_ID    Name   Age  Marks       City
0         1001    Aman  22.0   85.0      Delhi
1         1002   Priya  21.0    NaN     Mumbai
2         1003   Rahul   NaN   78.0  Bangalore
3         1004   Sneha  23.0   92.0        NaN
4         1005   Arjun  20.0   67.0    Chennai
5         1006     NaN  22.0   74.0  Hyderabad
6         1007   Meena  21.0    NaN       Pune
7         1008   Karan  24.0   88.0    Kolkata
8         1009  Anjali   NaN   95.0      Delhi
9         1010   Rohit  22.0   56.0        NaN
10        1011   Pooja  23.0   81.0     Mumbai
11        1012   Vikas  20.0    NaN  Bangalore
12        1013    Neha   NaN   73.0    Chennai
13        1014   Sahil  21.0   64.0  Hyderabad
14        1015   Divya  22.0    NaN       Pune
15        1016   Ayush  24.0   90.0    Kolkata
16        1017  Ritika   NaN   85.0        NaN
17        1018  Manish  20.0   58.0      Delhi
18        1019   Komal  23.0    NaN     Mumbai
19        1020   Nitin  21.0   76.0  Bangalore
20        1021  Simran   NaN   89.0    Chennai
21        1022   Varun  22.0   61.0        NaN
22        1023   Tanya  20.0    NaN       Pune
23        1024  Deepak  24.0   94.0    Kolkata
24        1025   Kavya   NaN   72.0      Delhi

In [98]:
csv_file['Age'].interpolate(limit_area='inside')

0     22.0
1     21.0
2     22.0
3     23.0
4     20.0
5     22.0
6     21.0
7     24.0
8     23.0
9     22.0
10    23.0
11    20.0
12    20.5
13    21.0
14    22.0
15    24.0
16    22.0
17    20.0
18    23.0
19    21.0
20    21.5
21    22.0
22    20.0
23    24.0
24     NaN
Name: Age, dtype: float64

In [99]:
csv_file['Age'].interpolate(limit_area='outside')

0     22.0
1     21.0
2      NaN
3     23.0
4     20.0
5     22.0
6     21.0
7     24.0
8      NaN
9     22.0
10    23.0
11    20.0
12     NaN
13    21.0
14    22.0
15    24.0
16     NaN
17    20.0
18    23.0
19    21.0
20     NaN
21    22.0
22    20.0
23    24.0
24    24.0
Name: Age, dtype: float64

In [102]:
csv_file['Age']=csv_file['Age'].interpolate(limit_direction='both',limit=2,inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\51548711.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  csv_file['Age']=csv_file['Age'].interpolate(limit_direction='both',limit=2,inplace=True)