In [2]:
import pandas as pd

data = {
    "name": ["Siya", "Aman"],
    "marks": [90, 85]
}

df = pd.DataFrame(data)

print(df.loc[0])

name     Siya
marks      90
Name: 0, dtype: object

In [1]:
import pandas as pd

In [2]:
csv_file=pd.read_csv("C:\\Users\\DELL\\Downloads\\sample_data_25x5.csv")

In [3]:
csv_file

    Unnamed: 0  Student_ID        Name  Age  Marks       City
0            0        1001   Student_1   23     57      Delhi
1            1        1002   Student_2   19     96     Mumbai
2            2        1003   Student_3   18     52      Delhi
3            3        1004   Student_4   20     84  Hyderabad
4            4        1005   Student_5   21     53    Chennai
5            5        1006   Student_6   18     85  Bangalore
6            6        1007   Student_7   21     95  Bangalore
7            7        1008   Student_8   22     89  Hyderabad
8            8        1009   Student_9   19     55     Mumbai
9            9        1010  Student_10   18     52      Delhi
10          10        1011  Student_11   23     75  Bangalore
11          11        1012  Student_12   24     63     Mumbai
12          12        1013  Student_13   20     97  Hyderabad
13          13        1014  Student_14   19     52    Chennai
14          14        1015  Student_15   19     64    Chennai
15          15        1016  Student_16   21     73    Chennai
16          16        1017  Student_17   23     91    Chennai
17          17        1018  Student_18   23     88      Delhi
18          18        1019  Student_19   24     97     Mumbai
19          19        1020  Student_20   21     84    Chennai
20          20        1021  Student_21   19     71    Chennai
21          21        1022  Student_22   21     93  Hyderabad
22          22        1023  Student_23   24     73  Hyderabad
23          23        1024  Student_24   19     94    Chennai
24          24        1025  Student_25   20     51  Hyderabad

In [5]:
csv_file.loc[:,['Student_ID','Name']]

    Student_ID        Name
0         1001   Student_1
1         1002   Student_2
2         1003   Student_3
3         1004   Student_4
4         1005   Student_5
5         1006   Student_6
6         1007   Student_7
7         1008   Student_8
8         1009   Student_9
9         1010  Student_10
10        1011  Student_11
11        1012  Student_12
12        1013  Student_13
13        1014  Student_14
14        1015  Student_15
15        1016  Student_16
16        1017  Student_17
17        1018  Student_18
18        1019  Student_19
19        1020  Student_20
20        1021  Student_21
21        1022  Student_22
22        1023  Student_23
23        1024  Student_24
24        1025  Student_25

In [ ]:
csv_file.loc[[2,5],:]  #to find the selected rows and columns

   Unnamed: 0  Student_ID       Name  Age  Marks       City
2           2        1003  Student_3   18     52      Delhi
5           5        1006  Student_6   18     85  Bangalore

In [ ]:
csv_file.iloc[0]  #gives the specified position data

Unnamed: 0            0
Student_ID         1001
Name          Student_1
Age                  23
Marks                57
City              Delhi
Name: 0, dtype: object

In [ ]:
csv_file.drop('Age',axis=1)   #to drop or delect the row and column

    Unnamed: 0  Student_ID        Name  Marks       City
0            0        1001   Student_1     57      Delhi
1            1        1002   Student_2     96     Mumbai
2            2        1003   Student_3     52      Delhi
3            3        1004   Student_4     84  Hyderabad
4            4        1005   Student_5     53    Chennai
5            5        1006   Student_6     85  Bangalore
6            6        1007   Student_7     95  Bangalore
7            7        1008   Student_8     89  Hyderabad
8            8        1009   Student_9     55     Mumbai
9            9        1010  Student_10     52      Delhi
10          10        1011  Student_11     75  Bangalore
11          11        1012  Student_12     63     Mumbai
12          12        1013  Student_13     97  Hyderabad
13          13        1014  Student_14     52    Chennai
14          14        1015  Student_15     64    Chennai
15          15        1016  Student_16     73    Chennai
16          16        1017  Student_17     91    Chennai
17          17        1018  Student_18     88      Delhi
18          18        1019  Student_19     97     Mumbai
19          19        1020  Student_20     84    Chennai
20          20        1021  Student_21     71    Chennai
21          21        1022  Student_22     93  Hyderabad
22          22        1023  Student_23     73  Hyderabad
23          23        1024  Student_24     94    Chennai
24          24        1025  Student_25     51  Hyderabad

In [10]:
csv_file.drop(0,axis=0)

    Unnamed: 0  Student_ID        Name  Age  Marks       City
1            1        1002   Student_2   19     96     Mumbai
2            2        1003   Student_3   18     52      Delhi
3            3        1004   Student_4   20     84  Hyderabad
4            4        1005   Student_5   21     53    Chennai
5            5        1006   Student_6   18     85  Bangalore
6            6        1007   Student_7   21     95  Bangalore
7            7        1008   Student_8   22     89  Hyderabad
8            8        1009   Student_9   19     55     Mumbai
9            9        1010  Student_10   18     52      Delhi
10          10        1011  Student_11   23     75  Bangalore
11          11        1012  Student_12   24     63     Mumbai
12          12        1013  Student_13   20     97  Hyderabad
13          13        1014  Student_14   19     52    Chennai
14          14        1015  Student_15   19     64    Chennai
15          15        1016  Student_16   21     73    Chennai
16          16        1017  Student_17   23     91    Chennai
17          17        1018  Student_18   23     88      Delhi
18          18        1019  Student_19   24     97     Mumbai
19          19        1020  Student_20   21     84    Chennai
20          20        1021  Student_21   19     71    Chennai
21          21        1022  Student_22   21     93  Hyderabad
22          22        1023  Student_23   24     73  Hyderabad
23          23        1024  Student_24   19     94    Chennai
24          24        1025  Student_25   20     51  Hyderabad